routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

// Route::get('/dashboard', function () {
//     return view('private.dashboard');
// })->name('dashboard');

Route::get('/dashboard/mylistings', function () {
    return view('private.mylistings');
})->name('mylistings');

Route::get('/dashboard/placeanad', function () {
    return view('private.placeanad');
})->name('placeanad');

Route::get('/dashboard/messages', function () {
    return view('private.messages');
})->name('messages');

Route::resource('private.ad', 'AdController');
 
Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');


//Management of Adds 
Route::get('/API/Rest/V1/getAllAds','PublicAdController@getAllAds');

app/Ad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
    //
    public $timestamps = true;
    protected $fillable = [
        'id_ad', 'advertiser_type', 'fee_applies','rent_type', 'proprety_type', 'youtube_url','email_contact',
        'phone_contact', 'id_address','id_room_type', 'id_tenancy_detail', 'id_existing_tenant','id_preferance',
        'id_bedroom', 'id'//user
    ];
}

app/Http/Controllers/AdController.php
<?php

namespace App\Http\Controllers;

use App\Ad;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class AdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($account)
    {
        //
        $ads=DB::table('ads')
            ->where('id', '=', $account)
            ->get();
        //dd($ads);
        return view('private.ad.index',compact('account','ads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($account)
    {
        //
        return view('private.ad.create',compact('account'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$account)
    {
        //
    
        $this->validate($request,[
            'advertiser_type'=>'required',
            'postcode'=>'required',
            'house_number'=>'required',
            'town'=>'required'
        ]);
       
        //Save Included
        $idIcluded=$this->saveIncludeds(
            $request->includeds
        );

        //Save tenancy
        $idTenancy=$this->saveTenancy(
            $idIcluded,$request->tenancyLength
            ,$request->monthlyRent,$request->maxTenancy
            ,$request->depositAmount,$request->maxNumberTenant
            ,$request->housingBeenfit,$request->referenceRequired
            ,$request->billsIncluded
        );
        //Save Preference
        $idPreference=$this->savePreference(
            $request->gender,$request->occupation
            ,$request->pets,$request->tenantAge,$request->couples
            ,$request->vegetarian
        );
        //Save Address
        $idAddress=$this->saveAddress(
            $request->postcode,$request->house_number,
            $request->address_line_1,$request->address_line_2
            ,$request->town
        );
        
        //Save existing_tenants
        $idExistingTenants=$this->saveExistingTenants(
            $request->existingTenants
        );
        
        //Save Room types
        $idRoomTypes=$this->saveRoomType(
            $request->date_available,
            $request->property_type,
            $request->room_type,
            $request->available_couple
        );

        //Save Bedrooms
        $idBedrooms=$this->saveBedroom(
            $request->bedRoomSelection
        );
        
        //Save ads
        $idAds=$this->saveAds(
            $request->advertiser_type,
            $request->fee_applies,
            $request->rent_type,
            $request->proprety_type,
            $request->youtube_url,
            $request->email_contact,
            $request->phone_contact,
            $idAddress,
            $idRoomTypes,
            $idTenancy,
            $idExistingTenants,
            $idPreference,
            $idBedrooms,
            $account
        );
        //Save photo
        $this->savePhotos($idAds,$request->photos);

        $ads=DB::table('ads')
                ->where('id', '=', $account)
                ->get();
        return view('private.ad.index',compact('account','ads'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function show(Ad $ad)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function edit(Ad $ad)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ad $ad)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_ad,$account)
    {
        //
    }
    //Save Includs
    private function saveIncludeds($selectionIncludeds)
    {
        $council=false;
        $water=false;
        $electrecity=false;
        $gas=false;
        $wifi=false;
        $tv=false;
        $licence=false;
        $cleaning=false;
        if(!(is_null($selectionIncludeds)))
        {
            $nSelection = count($selectionIncludeds);
            for($i=0; $i < $nSelection; $i++)
            {
                $numberVal = $selectionIncludeds[$i];
                if ($numberVal == "1"){
                    $council=true;
                }
                if ($numberVal == "2"){
                    $water=true;
                } 
                if ($numberVal == "3"){
                    $electrecity=true;
                }
                if ($numberVal == "4"){
                    $gas=true;
                }
                if ($numberVal == "5"){
                    $wifi=true;
                }
                if ($numberVal == "6"){
                    $tv=true;
                }
                if ($numberVal == "7"){
                    $licence=true;
                }
                if ($numberVal == "8"){
                    $cleaning=true;
                }
            }
        }
        $id_included_last= DB::table('includeds')-> insertGetId(array(
            'council_tax'=>$council,
            'water'=>$water,
            'electricity'=>$electrecity, 
            'gas'=>$gas,
            'wifi'=> $wifi,
            'tv'=>$tv,
            'license'=>$licence,
            'cleaning'=>$cleaning
        ));

        
        return $id_included_last;
    }

    //Save Tenancy
    private function saveTenancy($idIcluded,$tenancyLength,$monthlyRent,$maxTenancy
                                ,$depositAmount,$maxNumberTenant
                                ,$housingBeenfit,$referenceRequired
                                ,$billsIncluded)
    {
        if($housingBeenfit=="on")
            $housingBeenfit=true;
        else
            $housingBeenfit=false;
        if($referenceRequired=="on")
            $referenceRequired=true;
        else
            $referenceRequired=false;
        if($billsIncluded=="on")
            $billsIncluded=true;
        else
            $billsIncluded=false;

        $id_tenancy_last= DB::table('tenancy_details')-> insertGetId(array(
            'monthly_rent'=>$monthlyRent,
            'min_tenancy_length'=>$tenancyLength,
            'earlest_move_date'=>null,  //A  refaire
            'weekly_rent'=>null,//A  refaire
            'max_tenancy_length'=> $maxTenancy,
            'deposit_amount'=>$depositAmount,
            'max_tenants'=>$maxNumberTenant,
            'housing_beenfit'=>$housingBeenfit,
            'reference_required'=>$referenceRequired,
            'bills_included'=>$billsIncluded,
            'id_included'=>$idIcluded,

        ));
        return $id_tenancy_last;
    }
    private function savePreference($gender,$occupation
                    ,$pets,$tenantAge,$couples,$vegetarian)
    {
        if($pets=="on")
            $pets=true;
        else
            $pets=false;
        if($tenantAge=="on")
            $tenantAge=true;
        else
            $tenantAge=false;
        if($couples=="on")
            $couples=true;
        else
            $couples=false;
        if($vegetarian=="on")
            $vegetarian=true;
        else
            $vegetarian=false;
        $id_preference_last= DB::table('preferances')-> insertGetId(array(
            'gender'=>$gender,
            'occupation'=>$occupation,
            'pets'=>$pets,   
            'age_tenant'=>$tenantAge, 
            'couple_welcome'=> $couples,
            'vegetarian'=>$vegetarian

        ));
        return $id_preference_last;
    }

    private function saveAddress($postcode,$house_number,
            $address_line_1,$address_line_2
            ,$town)
    {
        $id_address_last=DB::table('addresses')-> insertGetId(array(
            'postcode'=>$postcode,
            'house_number'=>$house_number,
            'address_line_1'=>$address_line_1, 
            'address_line_2'=>$address_line_2,
            'town'=> $town
        ));
        return $id_address_last;
    }

    private function saveExistingTenants(
        $existingTenants
    )
    {
        $hates_football=false;
        $vegetarian=false;
        $professional=false;
        $student=false;
        $professional_student=false;
        $cat=false;
        $dog=false;
        if(!(is_null($existingTenants)))
        {
            $nSelection = count($existingTenants);
            for($i=0; $i < $nSelection; $i++)
            {
                $numberVal = $existingTenants[$i];
                if ($numberVal == "1"){
                    $hates_football=true;
                }
                if ($numberVal == "2"){
                    $vegetarian=true;
                } 
                if ($numberVal == "3"){
                    $professional=true;
                }
                if ($numberVal == "4"){
                    $student=true;
                }
                if ($numberVal == "5"){
                    $professional_student=true;
                }
                if ($numberVal == "6"){
                    $cat=true;
                }
                if ($numberVal == "7"){
                    $dog=true;
                }
            }
        }
        $id_existing_tenants=DB::table('existing_tenants')-> insertGetId(array(
            'hates_football'=>$hates_football,
            'vegetarian'=>$vegetarian,
            'professional'=>$professional, 
            'student'=>$student,
            'professional_student'=> $professional_student,
            'cat'=>$cat,
            'dog'=>$dog,
        ));

resources/views/private/ad/index.blade.php
@extends('layouts.private')

@section('content')

<div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"> My Listings </h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        My Listings
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Ref #</th>
                                        <th>Address</th>
                                        <th>Created</th>
                                        <th>Publish</th>
                                        <th>Remove</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($ads as $ad)
                                    <tr class="odd gradeX">
                                        <td>{{$ad->id_ad}}</td>
                                        <?php 
                                            $postcode=DB::table('addresses')->where('id_address',$ad->id_address)->get()->first()->postcode;
                                            $house_number=DB::table('addresses')->where('id_address',$ad->id_address)->get()->first()->house_number;
                                            $address_line_1=DB::table('addresses')->where('id_address',$ad->id_address)->get()->first()->address_line_1;
                                            $town=DB::table('addresses')->where('id_address',$ad->id_address)->get()->first()->town;
                                         ?>
                                        <td>House N°: {{$house_number}},{{$address_line_1}},{{$postcode}},{{$town}}</td>
                                        <td>{{$ad->created_at}}</td>
                                        <td class="center"><input type="button" value="Duplicate" class="btn btn-ms btn-primary"></td>
                                        <td>
                                            <form
                                            action="{{route('private.ad.destroy',['ad'=>$ad->id_ad,'account'=>$account])}}"
                                            method="POST"
                                            onsubmit="return confirm('Etes vous sur ?');"
                                            >
                                                {{csrf_field()}}
                                                {{method_field('DELETE')}}
                                                <input type="submit" value="Remove" class="btn btn-ms btn-danger">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
                <!-- /.col-lg-12 -->
        </div>
</div>
<!-- Content -->


@endsection