routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('index');

// Route::get('/dashboard', function () {
//     return view('private.dashboard');
// })->name('dashboard');

Route::get('/dashboard/mylistings', function () {
    return view('private.mylistings');
})->name('mylistings');

Route::get('/dashboard/placeanad', function () {
    return view('private.placeanad');
})->name('placeanad');

Route::get('/dashboard/messages', function () {
    return view('private.messages');
})->name('messages');

Route::resource('private.ad', 'AdController');
 
Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');


//Management of Adds 
Route::get('/API/Rest/V1/getAllAds','PublicAdController@getAllAds');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Sheffieldrooms</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="file-input/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script> 
    <script src="file-input/js/plugins/sortable.min.js"></script>
    <script src="file-input/js/fileinput.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>

    
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Sheffieldrooms
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/private.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sheffieldrooms Dashboard</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{asset('template-sb-admin/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">
    <!-- fileinput -->
    <link href="{{asset('file-input/css/fileinput.min.css')}}" media="all" rel="stylesheet" type="text/css" />
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script> 
    <!-- DataTables CSS -->
    <link href="{{asset('template-sb-admin/vendor/datatables-plugins/dataTables.bootstrap.css')}}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{{asset('template-sb-admin/vendor/datatables-responsive/dataTables.responsive.css')}}" rel="stylesheet">

    <!-- Latest compiled and fileinput JavaScript -->
    <script src="{{asset('file-input/js/plugins/sortable.min.js')}}"></script>
    <script src="{{asset('file-input/js/fileinput.min.js')}}"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>

    <!-- MetisMenu CSS -->
    <link href="{{asset('template-sb-admin/vendor/metisMenu/metisMenu.min.css')}}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{asset('template-sb-admin/dist/css/sb-admin-2.css')}}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{asset('template-sb-admin/vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">

    <!-- Bootstrap checkbox -->
    <script src="{{asset('bootstrap-checkbox/js/bootstrap-checkbox.js')}}" defer></script>
    
    
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{route('index')}}">Sheffieldrooms</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                <i class="fa fa-sign-out fa-fw"></i>{{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        
                         </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{{route('dashboard')}}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="{{route('private.ad.index',['account'=>$account])}}"><i class="fa fa-table fa-fw"></i> My Listings</a>
                        </li>
                        <li>
                            <a href="{{route('private.ad.create',['account'=>$account])}}"><i class="fa fa-plus fa-fw"></i> Place an Ad</a>
                        </li>
                        <li>
                            <a class="btn disabled" href="{{route('messages')}}"><i class="fa fa-envelope fa-fw"></i> Messages</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        @yield('content')
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <!-- <script src="{{asset('template-sb-admin/vendor/jquery/jquery.min.js')}}"></script> -->

    <!-- Bootstrap Core JavaScript -->
    <script src="{{asset('template-sb-admin/vendor/bootstrap/js/bootstrap.min.js')}}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{asset('template-sb-admin/vendor/metisMenu/metisMenu.min.js')}}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{asset('template-sb-admin/dist/js/sb-admin-2.js')}}"></script>

    <!-- DataTables JavaScript -->
    <script src="{{asset('template-sb-admin/vendor/datatables/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('template-sb-admin/vendor/datatables-plugins/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('template-sb-admin/vendor/datatables-responsive/dataTables.responsive.js')}}"></script>
    <script>
        $(document).ready(function() {
            $('#dataTables-example').DataTable({
                responsive: true
            });
            $(':checkbox').checkboxpicker();
        });
        
    </script>
</body>

</html>

resources/views/layouts/sheffieldrooms.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Meta Tag -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="sheffieldrooms">
		<meta name="keywords" content="real estate, property, property search, agent, apartments, booking, business, idx, housing, real estate agency, rental">
		<meta name="author" content="unicoder">
         <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title>Sheffieldrooms</title>
		<!-- Favicon -->
		<link rel="shortcut icon" href="img/favicon.ico">
		
		<!-- Bootstrap -->
		<link rel="stylesheet" href="css/bootstrap.css">
		<link rel="stylesheet" href="css/style.css">
		<link rel="stylesheet" href="css/font-awesome.css">
		<link rel="stylesheet" href="fonts/flaticon.css">
		<link rel="stylesheet" href="css/colors/blue.css">
		<link rel="stylesheet" href="css/jslider.css">
		<link rel="stylesheet" href="css/responsive.css">
		<link rel="stylesheet" href="css/loader.css">
		
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		
	</head>
	<body class="pagewrap property-list-page">
		
		<!-- Page Loader -->
		<div class="loading-page">
			<div class="sk-circle">
			  <div class="sk-circle1 sk-child"></div>
			  <div class="sk-circle2 sk-child"></div>
			  <div class="sk-circle3 sk-child"></div>
			  <div class="sk-circle4 sk-child"></div>
			  <div class="sk-circle5 sk-child"></div>
			  <div class="sk-circle6 sk-child"></div>
			  <div class="sk-circle7 sk-child"></div>
			  <div class="sk-circle8 sk-child"></div>
			  <div class="sk-circle9 sk-child"></div>
			  <div class="sk-circle10 sk-child"></div>
			  <div class="sk-circle11 sk-child"></div>
			  <div class="sk-circle12 sk-child"></div>
			</div>
		</div>
		<!-- End Loader -->
		
		<!-- Color Settings -->
		<!-- <div class="blue" data-path="css/colors/blue.css" data-image="img/logo1_blue.png" data-target="img/logo2_blue.png"></div> -->
		<!-- <div class="color-panel">
			<div class="on-panel"><img src="img/icons/settings.png" alt=""></div>
			<div class="panel-box">
				<span class="panel-title">Change Colors</span>
				<ul class="color-box">
					<li class="green" data-path="css/colors/green.css" data-image="img/logo1.png" data-target="img/logo2.png"></li>
					<li class="blue" data-path="css/colors/blue.css" data-image="img/logo1_blue.png" data-target="img/logo2_blue.png"></li>
					<li class="red" data-path="css/colors/red.css" data-image="img/logo1_red.png" data-target="img/logo2_red.png"></li>
					<li class="purple" data-path="css/colors/purple.css" data-image="img/logo1_purple.png" data-target="img/logo2_purple.png"></li>
					<li class="yellow" data-path="css/colors/yellow.css" data-image="img/logo1_yellow.png" data-target="img/logo2_yellow.png"></li>
					<li class="orange" data-path="css/colors/orange.css" data-image="img/logo1_orange.png" data-target="img/logo2_orange.png"></li>
					<li class="magento" data-path="css/colors/magento.css" data-image="img/logo1_magento.png" data-target="img/logo2_magento.png"></li>
					<li class="turquoise" data-path="css/colors/turquoise.css" data-image="img/logo1_turquoise.png" data-target="img/logo2_turquoise.png"></li>
					<li class="lemon" data-path="css/colors/lemon.css" data-image="img/logo1_lemon.png" data-target="img/logo2_lemon.png"></li>
				</ul>
			</div>
		</div> -->
		<!-- End Color Settings -->
		
		<header id="header">
			<!-- Top Header Start -->
			<div id="top_header">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-sm-3">
							<div class="top_contact">
								<a class="navbar-brand" href="{{route('index')}}"><img class="nav-logo" src="img/logo.png" alt=""></a>
							</div>
						</div>
						<div class="col-md-3 col-sm-3">
							<div class="top_contact">
								<a class="navbar-brand" href="{{route('index')}}"><img class="nav-logo" src="img/slogo.png" alt=""></a>
							</div>
						</div>
						<div class="col-md-5 col-sm-6">
							<div class="top_right">
								<ul>
									<!-- <li>
										<div class="lan-drop"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Eng <span class="caret"></span></a>
											<ul class="dropdown-menu">
												<li><a href="#">sp</a></li>
												<li><a href="#">ch</a></li>
												<li><a href="#">ud</a></li>
											</ul>
										</div>
									</li> -->
									<li><a href="{{route('login')}}"><button  class="btn btn-primary btn-sm" >Place an AD</button></a></li>
									<!-- <li><a href="{{route('register')}}"><button class="btn btn-default btn-sm" >Register</button></a></li>
									<li><a href="{{route('login')}}" ><button class="btn btn-default btn-sm" >Log In</button></a></li> -->
									<!-- Authentication Links -->
									@guest
										@if (Route::has('register'))
											<li class="nav-item">
												<a href="{{ route('register') }}"><button class="btn btn-default btn-sm" >Register</button></a>
											</li>
										@endif
										<li  >
											<a   href="{{ route('login') }}"><button class="btn btn-default btn-sm" >Log In</button></a>
										</li>
									@else
										<li  >
											<div class="btn-group lan-drop" role="group">
												<button type="button" class="btn btn-default btn-sm  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="border-left-color: rgb(209, 209, 209);">
													{{ Auth::user()->name }} 
													<span class="caret"></span>
												</button>
												<ul class="dropdown-menu">
													<li>
														<a   href="{{ route('login') }}">My profile</a>
													</li>
													<li>
														<a class="dropdown-item" href="{{ route('logout') }}"
														onclick="event.preventDefault();
																		document.getElementById('logout-form').submit();">
															{{ __('Logout') }}
														</a>

														<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
															@csrf
														</form>
													</li>
												</ul>
											</div>
										</li>
									@endguest
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Top Header End --> 
			
		</header>
            <!-- Banner Section Start -->
		<section>
			
        </section>

        @yield('content')
 
		
		<!-- Bottom Footer Start -->
		<div id="bottom_footer">
			<div class="reserve_text"> <span>Copyright &copy; 2017 Uniland All Right Reserve</span> </div>
		</div>
		<!-- Bottom Footer End -->
		
		<!-- Scroll to top -->
		<div class="scroll-to-top">
			<a href="#" class="scroll-btn" data-target=".pagewrap"><i class="fa fa-angle-up" aria-hidden="true"></i></a>
		</div>
		 
		<!-- End Scroll To top -->
        <!-- All Javascript Plugin File here -->
		<script src="js/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/bootstrap-select.js"></script>
		<script src="js/YouTubePopUp.jquery.js"></script>
		<script src="js/jquery.fancybox.pack.js"></script>
		<script src="js/jquery.fancybox-media.js"></script>
		<script src="js/owl.js"></script>
		<script src="js/mixitup.js"></script>
		<script src="js/wow.js"></script>
		<script src="js/jshashtable-2.1_src.js"></script> 
		<script src="js/jquery.numberformatter-1.2.3.js"></script> 
		<script src="js/tmpl.js"></script>
		<script src="js/jquery.dependClass-0.1.js"></script> 
		<script src="js/draggable-0.1.js"></script> 
		<script src="js/jquery.slider.js"></script>
		<script src="js/jquery.barrating.js"></script>
		<script src="js/custom.js"></script>
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-106986305-1', 'auto');
			ga('send', 'pageview');
			
			
		</script>
		
	</body>
</html>	